print("Hello world!")
print("Hello world!")
print("Hello sun!")
print("Hello sky!")
print("Hello world!", end=" ")
print("Hello sun!", end="!! ")
print("Hello sky!", end="!!!\n")
movies = ['Matilda', 'Christmas', 'Sherlock Holmes', 'Dog', 'Eleven']
movies.append('Grey')      
print(movies)
print(1995)
print('1995')